{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","title":"blurEffectStyle","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"blurEffectStyle"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"blurEffectStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIBlurEffect","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBlurEffect"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBlurEffectStyle","text":"Style"}],"externalID":"c:objc(cs)MBBackgroundView(py)blurEffectStyle","modules":[{"name":"GCCardReader"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"blurEffectStyle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBlurEffect","text":"UIBlurEffect"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIBlurEffectStyle","text":"Style","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","abstract":[{"text":"The blur effect style, when using MBProgressHUDBackgroundStyleBlur.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to UIBlurEffectStyleLight.","type":"text"}],"variants":[{"paths":["\/documentation\/gccardreader\/mbbackgroundview\/blureffectstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gccardreader\/mbbackgroundview\/blureffectstyle"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBackgroundView\/blurEffectStyle"},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBackgroundView"]]},"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBBackgroundView/blurEffectStyle":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The blur effect style, when using MBProgressHUDBackgroundStyleBlur."},{"type":"text","text":" "},{"type":"text","text":"Defaults to UIBlurEffectStyleLight."}],"url":"\/documentation\/gccardreader\/mbbackgroundview\/blureffectstyle","kind":"symbol","title":"blurEffectStyle","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBackgroundView\/blurEffectStyle","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"blurEffectStyle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBlurEffect","text":"UIBlurEffect"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBlurEffectStyle","text":"Style"}],"navigatorTitle":[{"text":"blurEffectStyle","kind":"identifier"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBBackgroundView":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBBackgroundView","kind":"identifier"}],"navigatorTitle":[{"text":"MBBackgroundView","kind":"identifier"}],"role":"symbol","url":"\/documentation\/gccardreader\/mbbackgroundview","title":"MBBackgroundView","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBackgroundView","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"blurEffectStyle","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"blurEffectStyle","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIBlurEffectStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBlurEffectStyle"},{"kind":"text","text":" "},{"text":"blurEffectStyle","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBBackgroundView~1blurEffectStyle\/title","value":"blurEffectStyle","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBBackgroundView~1blurEffectStyle\/fragments","value":[{"text":"blurEffectStyle","kind":"identifier"}],"op":"replace"},{"value":"MBBackgroundView","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBBackgroundView\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBBackgroundView\/fragments","op":"replace","value":[{"text":"MBBackgroundView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}