{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBRoundProgressView"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gccardreader\/mbroundprogressview\/backgroundtintcolor"]},{"paths":["\/documentation\/gccardreader\/mbroundprogressview\/backgroundtintcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBRoundProgressView\/backgroundTintColor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicator background (non-progress) color."},{"type":"text","text":" "},{"type":"text","text":"Only applicable on iOS versions older than iOS 7."},{"type":"text","text":" "},{"text":"Defaults to translucent white (alpha 0.1).","type":"text"}],"metadata":{"role":"symbol","symbolKind":"property","title":"backgroundTintColor","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"backgroundTintColor"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundTintColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"externalID":"c:objc(cs)MBRoundProgressView(py)backgroundTintColor","modules":[{"name":"GCCardReader"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"backgroundTintColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBRoundProgressView/backgroundTintColor":{"navigatorTitle":[{"kind":"identifier","text":"backgroundTintColor"}],"kind":"symbol","url":"\/documentation\/gccardreader\/mbroundprogressview\/backgroundtintcolor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundTintColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"abstract":[{"type":"text","text":"Indicator background (non-progress) color."},{"type":"text","text":" "},{"type":"text","text":"Only applicable on iOS versions older than iOS 7."},{"type":"text","text":" "},{"type":"text","text":"Defaults to translucent white (alpha 0.1)."}],"title":"backgroundTintColor","type":"topic","role":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBRoundProgressView\/backgroundTintColor"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBRoundProgressView":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A progress view for showing definite progress by filling up a circle (pie chart)."}],"kind":"symbol","title":"MBRoundProgressView","url":"\/documentation\/gccardreader\/mbroundprogressview","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBRoundProgressView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBRoundProgressView"}],"navigatorTitle":[{"text":"MBRoundProgressView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"backgroundTintColor","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"backgroundTintColor"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"backgroundTintColor"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBRoundProgressView~1backgroundTintColor\/title","value":"backgroundTintColor","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBRoundProgressView~1backgroundTintColor\/fragments","value":[{"text":"backgroundTintColor","kind":"identifier"}]},{"value":"MBRoundProgressView","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBRoundProgressView\/title"},{"value":[{"text":"MBRoundProgressView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBRoundProgressView\/fragments","op":"replace"}]}]}