{"metadata":{"roleHeading":"Instance Property","title":"progress","role":"symbol","externalID":"c:objc(cs)MBRoundProgressView(py)progress","modules":[{"name":"GCCardReader"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"progress","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"progress"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"progress"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBRoundProgressView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBRoundProgressView\/progress"},"abstract":[{"type":"text","text":"Progress (0.0 to 1.0)"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gccardreader\/mbroundprogressview\/progress"]},{"paths":["\/documentation\/gccardreader\/mbroundprogressview\/progress"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBRoundProgressView/progress":{"navigatorTitle":[{"text":"progress","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gccardreader\/mbroundprogressview\/progress","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"progress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"abstract":[{"type":"text","text":"Progress (0.0 to 1.0)"}],"type":"topic","title":"progress","role":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBRoundProgressView\/progress"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBRoundProgressView":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A progress view for showing definite progress by filling up a circle (pie chart)."}],"kind":"symbol","title":"MBRoundProgressView","url":"\/documentation\/gccardreader\/mbroundprogressview","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBRoundProgressView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBRoundProgressView"}],"navigatorTitle":[{"text":"MBRoundProgressView","kind":"identifier"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"progress"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"progress"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:f","text":"float","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"progress"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBRoundProgressView~1progress\/title","value":"progress"},{"value":[{"text":"progress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBRoundProgressView~1progress\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBRoundProgressView\/title","op":"replace","value":"MBRoundProgressView"},{"op":"replace","value":[{"kind":"identifier","text":"MBRoundProgressView"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBRoundProgressView\/fragments"}]}]}