{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBarProgressView"]]},"metadata":{"externalID":"c:objc(cs)MBBarProgressView(py)progressColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"title":"progressColor","navigatorTitle":[{"text":"progressColor","kind":"identifier"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"GCCardReader"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gccardreader\/mbbarprogressview\/progresscolor"]},{"paths":["\/documentation\/gccardreader\/mbbarprogressview\/progresscolor"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Bar progress color."},{"type":"text","text":" "},{"type":"text","text":"Defaults to white [UIColor whiteColor]."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBarProgressView\/progressColor"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"progressColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBBarProgressView/progressColor":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"progressColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"navigatorTitle":[{"kind":"identifier","text":"progressColor"}],"kind":"symbol","type":"topic","title":"progressColor","url":"\/documentation\/gccardreader\/mbbarprogressview\/progresscolor","abstract":[{"text":"Bar progress color.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Defaults to white [UIColor whiteColor]."}],"role":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBarProgressView\/progressColor"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBBarProgressView":{"navigatorTitle":[{"kind":"identifier","text":"MBBarProgressView"}],"role":"symbol","title":"MBBarProgressView","type":"topic","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBarProgressView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBBarProgressView"}],"url":"\/documentation\/gccardreader\/mbbarprogressview","abstract":[{"type":"text","text":"A flat bar progress view."}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"progressColor"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"progressColor"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":" * ","kind":"text"},{"text":"progressColor","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBBarProgressView~1progressColor\/title","value":"progressColor","op":"replace"},{"value":[{"kind":"identifier","text":"progressColor"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBBarProgressView~1progressColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBBarProgressView\/title","value":"MBBarProgressView"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBBarProgressView\/fragments","value":[{"kind":"identifier","text":"MBBarProgressView"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}