{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"MBProgressHUDBackgroundStyle.blur","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"blur"}],"navigatorTitle":[{"text":"MBProgressHUDBackgroundStyleBlur","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"GCCardReader"}],"role":"symbol","roleHeading":"Case","externalID":"c:@E@MBProgressHUDBackgroundStyle@MBProgressHUDBackgroundStyleBlur"},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDBackgroundStyle"]]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"UIVisualEffectView or UIToolbar.layer background view"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gccardreader\/mbprogresshudbackgroundstyle\/blur"]},{"paths":["\/documentation\/gccardreader\/mbprogresshudbackgroundstyle\/blur"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"blur","kind":"identifier"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDBackgroundStyle\/blur"},"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDBackgroundStyle":{"type":"topic","navigatorTitle":[{"text":"MBProgressHUDBackgroundStyle","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBProgressHUDBackgroundStyle"}],"abstract":[],"url":"\/documentation\/gccardreader\/mbprogresshudbackgroundstyle","title":"MBProgressHUDBackgroundStyle","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDBackgroundStyle","role":"symbol","kind":"symbol"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDBackgroundStyle/blur":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"blur","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDBackgroundStyle\/blur","navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDBackgroundStyleBlur"}],"type":"topic","url":"\/documentation\/gccardreader\/mbprogresshudbackgroundstyle\/blur","abstract":[{"type":"text","text":"UIVisualEffectView or UIToolbar.layer background view"}],"kind":"symbol","role":"symbol","title":"MBProgressHUDBackgroundStyle.blur"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"MBProgressHUDBackgroundStyleBlur","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"MBProgressHUDBackgroundStyleBlur","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MBProgressHUDBackgroundStyleBlur"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"MBProgressHUDBackgroundStyle","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDBackgroundStyle\/title"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDBackgroundStyle\/fragments","op":"replace","value":[{"text":"MBProgressHUDBackgroundStyle","kind":"identifier"}]},{"op":"replace","value":"MBProgressHUDBackgroundStyleBlur","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDBackgroundStyle~1blur\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDBackgroundStyle~1blur\/fragments","value":[{"kind":"identifier","text":"MBProgressHUDBackgroundStyleBlur"}]}]}]}