{"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDBackgroundStyle"]]},"variants":[{"paths":["\/documentation\/gccardreader\/mbprogresshudbackgroundstyle\/solidcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gccardreader\/mbprogresshudbackgroundstyle\/solidcolor"]}],"identifier":{"url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDBackgroundStyle\/solidColor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Solid color background"}],"sections":[],"metadata":{"externalID":"c:@E@MBProgressHUDBackgroundStyle@MBProgressHUDBackgroundStyleSolidColor","symbolKind":"case","navigatorTitle":[{"text":"MBProgressHUDBackgroundStyleSolidColor","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"solidColor","kind":"identifier"}],"title":"MBProgressHUDBackgroundStyle.solidColor","role":"symbol","modules":[{"name":"GCCardReader"}],"roleHeading":"Case"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"solidColor"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDBackgroundStyle/solidColor":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDBackgroundStyleSolidColor"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"solidColor"}],"abstract":[{"type":"text","text":"Solid color background"}],"url":"\/documentation\/gccardreader\/mbprogresshudbackgroundstyle\/solidcolor","title":"MBProgressHUDBackgroundStyle.solidColor","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDBackgroundStyle\/solidColor","role":"symbol","kind":"symbol"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDBackgroundStyle":{"type":"topic","navigatorTitle":[{"text":"MBProgressHUDBackgroundStyle","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBProgressHUDBackgroundStyle"}],"abstract":[],"url":"\/documentation\/gccardreader\/mbprogresshudbackgroundstyle","title":"MBProgressHUDBackgroundStyle","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDBackgroundStyle","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"MBProgressHUDBackgroundStyleSolidColor","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MBProgressHUDBackgroundStyleSolidColor","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MBProgressHUDBackgroundStyleSolidColor"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"MBProgressHUDBackgroundStyleSolidColor","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDBackgroundStyle~1solidColor\/title"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDBackgroundStyle~1solidColor\/fragments","value":[{"kind":"identifier","text":"MBProgressHUDBackgroundStyleSolidColor"}],"op":"replace"},{"value":"MBProgressHUDBackgroundStyle","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDBackgroundStyle\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDBackgroundStyle\/fragments","value":[{"kind":"identifier","text":"MBProgressHUDBackgroundStyle"}]}]}]}