{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"MBProgressHUDAnimationFade","kind":"identifier"}],"modules":[{"name":"GCCardReader"}],"externalID":"c:@E@MBProgressHUDAnimation@MBProgressHUDAnimationFade","role":"symbol","title":"MBProgressHUDAnimation.fade","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fade"}]},"abstract":[{"text":"Opacity animation","type":"text"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDAnimation"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"fade","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gccardreader\/mbprogresshudanimation\/fade"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gccardreader\/mbprogresshudanimation\/fade"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDAnimation\/fade"},"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDAnimation":{"type":"topic","url":"\/documentation\/gccardreader\/mbprogresshudanimation","title":"MBProgressHUDAnimation","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDAnimation","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MBProgressHUDAnimation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDAnimation"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDAnimation/fade":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDAnimation\/fade","abstract":[{"type":"text","text":"Opacity animation"}],"navigatorTitle":[{"text":"MBProgressHUDAnimationFade","kind":"identifier"}],"url":"\/documentation\/gccardreader\/mbprogresshudanimation\/fade","role":"symbol","title":"MBProgressHUDAnimation.fade","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fade","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MBProgressHUDAnimationFade"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MBProgressHUDAnimationFade","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MBProgressHUDAnimationFade","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDAnimation\/title","value":"MBProgressHUDAnimation"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDAnimation\/fragments","value":[{"text":"MBProgressHUDAnimation","kind":"identifier"}]},{"value":"MBProgressHUDAnimationFade","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDAnimation~1fade\/title","op":"replace"},{"value":[{"text":"MBProgressHUDAnimationFade","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDAnimation~1fade\/fragments","op":"replace"}]}]}