{"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDAnimation"]]},"identifier":{"url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDAnimation\/zoomIn","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@E@MBProgressHUDAnimation@MBProgressHUDAnimationZoomIn","navigatorTitle":[{"text":"MBProgressHUDAnimationZoomIn","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"GCCardReader"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"zoomIn","kind":"identifier"}],"title":"MBProgressHUDAnimation.zoomIn","symbolKind":"case","role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gccardreader\/mbprogresshudanimation\/zoomin"]},{"paths":["\/documentation\/gccardreader\/mbprogresshudanimation\/zoomin"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zoomIn","kind":"identifier"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Opacity + scale animation (zoom in style)","type":"text"}],"sections":[],"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDAnimation/zoomIn":{"role":"symbol","abstract":[{"text":"Opacity + scale animation (zoom in style)","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"zoomIn","kind":"identifier"}],"navigatorTitle":[{"text":"MBProgressHUDAnimationZoomIn","kind":"identifier"}],"title":"MBProgressHUDAnimation.zoomIn","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDAnimation\/zoomIn","url":"\/documentation\/gccardreader\/mbprogresshudanimation\/zoomin","type":"topic"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDAnimation":{"type":"topic","url":"\/documentation\/gccardreader\/mbprogresshudanimation","title":"MBProgressHUDAnimation","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDAnimation","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MBProgressHUDAnimation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDAnimation"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MBProgressHUDAnimationZoomIn","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"MBProgressHUDAnimationZoomIn","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"MBProgressHUDAnimationZoomIn"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"MBProgressHUDAnimationZoomIn","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDAnimation~1zoomIn\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDAnimation~1zoomIn\/fragments","value":[{"text":"MBProgressHUDAnimationZoomIn","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDAnimation\/title","op":"replace","value":"MBProgressHUDAnimation"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDAnimation\/fragments","value":[{"text":"MBProgressHUDAnimation","kind":"identifier"}]}]}]}