{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gccardreader\/mbprogresshudanimation\/zoomout"]},{"paths":["\/documentation\/gccardreader\/mbprogresshudanimation\/zoomout"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDAnimation"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDAnimation\/zoomOut","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","title":"MBProgressHUDAnimation.zoomOut","externalID":"c:@E@MBProgressHUDAnimation@MBProgressHUDAnimationZoomOut","symbolKind":"case","modules":[{"name":"GCCardReader"}],"navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDAnimationZoomOut"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoomOut"}],"role":"symbol"},"abstract":[{"type":"text","text":"Opacity + scale animation (zoom out style)"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zoomOut","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDAnimation":{"type":"topic","url":"\/documentation\/gccardreader\/mbprogresshudanimation","title":"MBProgressHUDAnimation","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDAnimation","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MBProgressHUDAnimation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDAnimation"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDAnimation/zoomOut":{"url":"\/documentation\/gccardreader\/mbprogresshudanimation\/zoomout","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDAnimation\/zoomOut","title":"MBProgressHUDAnimation.zoomOut","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"zoomOut","kind":"identifier"}],"abstract":[{"type":"text","text":"Opacity + scale animation (zoom out style)"}],"type":"topic","navigatorTitle":[{"text":"MBProgressHUDAnimationZoomOut","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"MBProgressHUDAnimationZoomOut","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBProgressHUDAnimationZoomOut","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MBProgressHUDAnimationZoomOut"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDAnimation\/title","value":"MBProgressHUDAnimation","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDAnimation\/fragments","value":[{"kind":"identifier","text":"MBProgressHUDAnimation"}]},{"value":"MBProgressHUDAnimationZoomOut","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDAnimation~1zoomOut\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDAnimation~1zoomOut\/fragments","value":[{"kind":"identifier","text":"MBProgressHUDAnimationZoomOut"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}