{"kind":"symbol","abstract":[{"type":"text","text":"Opacity + scale animation (zoom in when appearing zoom out when disappearing)"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gccardreader\/mbprogresshudanimation\/zoom"]},{"paths":["\/documentation\/gccardreader\/mbprogresshudanimation\/zoom"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"MBProgressHUDAnimation.zoom","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoom"}],"modules":[{"name":"GCCardReader"}],"roleHeading":"Case","externalID":"c:@E@MBProgressHUDAnimation@MBProgressHUDAnimationZoom","navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDAnimationZoom"}],"role":"symbol","symbolKind":"case"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDAnimation"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDAnimation\/zoom"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zoom","kind":"identifier"}]}]}],"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDAnimation":{"type":"topic","url":"\/documentation\/gccardreader\/mbprogresshudanimation","title":"MBProgressHUDAnimation","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDAnimation","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MBProgressHUDAnimation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDAnimation"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDAnimation/zoom":{"kind":"symbol","abstract":[{"type":"text","text":"Opacity + scale animation (zoom in when appearing zoom out when disappearing)"}],"role":"symbol","title":"MBProgressHUDAnimation.zoom","url":"\/documentation\/gccardreader\/mbprogresshudanimation\/zoom","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"zoom","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDAnimation\/zoom","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDAnimationZoom"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MBProgressHUDAnimationZoom"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBProgressHUDAnimationZoom","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"MBProgressHUDAnimationZoom"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"MBProgressHUDAnimation","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDAnimation\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDAnimation\/fragments","value":[{"text":"MBProgressHUDAnimation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDAnimation~1zoom\/title","value":"MBProgressHUDAnimationZoom","op":"replace"},{"value":[{"text":"MBProgressHUDAnimationZoom","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDAnimation~1zoom\/fragments"}]}]}