{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"webView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didFinish","kind":"externalParam"},{"kind":"text","text":" "},{"text":"navigation","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigation","text":"WKNavigation"},{"text":"!)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"extendedModule":"GCCardReader","roleHeading":"Instance Method","platforms":[{"name":"iOS","introducedAt":"13.0","unavailable":false,"deprecated":false,"beta":false}],"modules":[{"name":"GCCardReader"}],"externalID":"c:@CM@GCCardReader@objc(cs)GcCardReader(im)webView:didFinishNavigation:","title":"webView(_:didFinish:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"text":"didFinish","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)WKNavigation","text":"WKNavigation","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"role":"symbol","navigatorTitle":[{"text":"webView:didFinishNavigation:","kind":"identifier"}]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"WKNavigationDelegate.webView(_:didFinish:)"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/webView(_:didFinish:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/gccardreader\/gccardreader\/webview(_:didfinish:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gccardreader\/gccardreader\/webview(_:didfinish:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/WKNavigationDelegate-Implementations"]]},"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader/webView(_:didFinish:)":{"kind":"symbol","url":"\/documentation\/gccardreader\/gccardreader\/webview(_:didfinish:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"webView:didFinishNavigation:","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":", ","kind":"text"},{"text":"didFinish","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigation","text":"WKNavigation"},{"kind":"text","text":"!)"}],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/webView(_:didFinish:)","title":"webView(_:didFinish:)"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader/WKNavigationDelegate-Implementations":{"title":"WKNavigationDelegate Implementations","url":"\/documentation\/gccardreader\/gccardreader\/wknavigationdelegate-implementations","role":"collectionGroup","type":"topic","abstract":[],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/WKNavigationDelegate-Implementations","kind":"article"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader":{"kind":"symbol","url":"\/documentation\/gccardreader\/gccardreader","role":"symbol","type":"topic","navigatorTitle":[{"text":"GcCardReader","kind":"identifier"}],"abstract":[{"type":"text","text":"cCCardReader: Defines public class for the framework. Use the shared instance of this to use methods related to card scanning and NFC connection."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GcCardReader","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader","title":"GcCardReader"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"type":"topic","abstract":[{"type":"text","text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or perform OCR with the camera and then validate the result using the ICA API."}],"title":"GCCardReader","role":"collection","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","url":"\/documentation\/gccardreader"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"webView:didFinishNavigation:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"webView:didFinishNavigation:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"webView:"},{"text":"(","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":" *) ","kind":"text"},{"text":"webView","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didFinishNavigation:"},{"text":"(","kind":"text"},{"text":"WKNavigation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigation"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"navigation"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1GcCardReader~1webView(_:didFinish:)\/title","op":"replace","value":"webView:didFinishNavigation:"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1GcCardReader~1webView(_:didFinish:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didFinishNavigation:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1GcCardReader\/title","value":"GcCardReader"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1GcCardReader\/fragments","value":[{"text":"GcCardReader","kind":"identifier"}]}]}]}