{"identifier":{"url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/webView(_:didFail:withError:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@CM@GCCardReader@objc(cs)GcCardReader(im)webView:didFailNavigation:withError:","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"GCCardReader"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"webView:didFailNavigation:withError:"}],"title":"webView(_:didFail:withError:)","platforms":[{"beta":false,"introducedAt":"13.0","name":"iOS","deprecated":false,"unavailable":false}],"extendedModule":"GCCardReader","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"webView"},{"text":"(","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFail"},{"kind":"text","text":": "},{"text":"WKNavigation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigation"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/WKNavigationDelegate-Implementations"]]},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"WKNavigationDelegate.webView(_:didFail:withError:)"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"webView"},{"text":": ","kind":"text"},{"text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFail"},{"text":" ","kind":"text"},{"text":"navigation","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigation","text":"WKNavigation"},{"kind":"text","text":"!, "},{"text":"withError","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gccardreader\/gccardreader\/webview(_:didfail:witherror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gccardreader\/gccardreader\/webview(_:didfail:witherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader":{"kind":"symbol","url":"\/documentation\/gccardreader\/gccardreader","role":"symbol","type":"topic","navigatorTitle":[{"text":"GcCardReader","kind":"identifier"}],"abstract":[{"type":"text","text":"cCCardReader: Defines public class for the framework. Use the shared instance of this to use methods related to card scanning and NFC connection."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GcCardReader","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader","title":"GcCardReader"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader/WKNavigationDelegate-Implementations":{"title":"WKNavigationDelegate Implementations","url":"\/documentation\/gccardreader\/gccardreader\/wknavigationdelegate-implementations","role":"collectionGroup","type":"topic","abstract":[],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/WKNavigationDelegate-Implementations","kind":"article"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader/webView(_:didFail:withError:)":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/webView(_:didFail:withError:)","url":"\/documentation\/gccardreader\/gccardreader\/webview(_:didfail:witherror:)","role":"symbol","type":"topic","title":"webView(_:didFail:withError:)","kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"webView"},{"text":"(","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFail"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation"},{"kind":"text","text":"!, "},{"text":"withError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"webView:didFailNavigation:withError:","kind":"identifier"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"type":"topic","abstract":[{"type":"text","text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or perform OCR with the camera and then validate the result using the ICA API."}],"title":"GCCardReader","role":"collection","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","url":"\/documentation\/gccardreader"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"webView:didFailNavigation:withError:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"webView:didFailNavigation:withError:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"webView:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"webView","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didFailNavigation:"},{"text":"(","kind":"text"},{"text":"WKNavigation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigation"},{"text":" *) ","kind":"text"},{"text":"navigation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withError:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1GcCardReader\/title","op":"replace","value":"GcCardReader"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1GcCardReader\/fragments","op":"replace","value":[{"kind":"identifier","text":"GcCardReader"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1GcCardReader~1webView(_:didFail:withError:)\/title","op":"replace","value":"webView:didFailNavigation:withError:"},{"value":[{"kind":"text","text":"- "},{"text":"webView:didFailNavigation:withError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1GcCardReader~1webView(_:didFail:withError:)\/fragments","op":"replace"}]}]}