{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/WKNavigationDelegate-Implementations"},"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader"]]},"variants":[{"paths":["\/documentation\/gccardreader\/gccardreader\/wknavigationdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gccardreader\/gccardreader\/wknavigationdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"modules":[{"name":"GCCardReader"}],"roleHeading":"API Collection","title":"WKNavigationDelegate Implementations","role":"collectionGroup"},"topicSections":[{"identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/webView(_:didFail:withError:)","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/webView(_:didFinish:)"],"generated":true,"title":"Instance Methods"}],"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader/webView(_:didFail:withError:)":{"navigatorTitle":[{"kind":"identifier","text":"webView:didFailNavigation:withError:"}],"title":"webView(_:didFail:withError:)","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/webView(_:didFail:withError:)","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/gccardreader\/gccardreader\/webview(_:didfail:witherror:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"kind":"text","text":"("},{"text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didFail","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation"},{"text":"!, ","kind":"text"},{"text":"withError","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader":{"abstract":[{"text":"cCCardReader: Defines public class for the framework. Use the shared instance of this to use methods related to card scanning and NFC connection.","type":"text"}],"title":"GcCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader","url":"\/documentation\/gccardreader\/gccardreader","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GcCardReader","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GcCardReader"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader/webView(_:didFinish:)":{"abstract":[],"title":"webView(_:didFinish:)","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/webView(_:didFinish:)","url":"\/documentation\/gccardreader\/gccardreader\/webview(_:didfinish:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFinish"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"webView:didFinishNavigation:"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/webView(_:didFail:withError:)","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/webView(_:didFinish:)"]}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1GcCardReader~1webView(_:didFail:withError:)\/title","value":"webView:didFailNavigation:withError:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didFailNavigation:withError:"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1GcCardReader~1webView(_:didFail:withError:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1GcCardReader\/title","value":"GcCardReader"},{"value":[{"text":"GcCardReader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1GcCardReader\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1GcCardReader~1webView(_:didFinish:)\/title","value":"webView:didFinishNavigation:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"webView:didFinishNavigation:"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1GcCardReader~1webView(_:didFinish:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}