{"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.gamechange.GCCardReader\/objc(cs)UIView"],"title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.gamechange.GCCardReader\/objc(pl)NSCoding","doc:\/\/com.gamechange.GCCardReader\/objc(pl)NSObject","doc:\/\/com.gamechange.GCCardReader\/objc(pl)CALayerDelegate","doc:\/\/com.gamechange.GCCardReader\/s7CVarArgP","doc:\/\/com.gamechange.GCCardReader\/s28CustomDebugStringConvertibleP","doc:\/\/com.gamechange.GCCardReader\/s23CustomStringConvertibleP","doc:\/\/com.gamechange.GCCardReader\/SQ","doc:\/\/com.gamechange.GCCardReader\/SH","doc:\/\/com.gamechange.GCCardReader\/s8SendableP","doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIAppearance","doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIAppearanceContainer","doc:\/\/com.gamechange.GCCardReader\/objc(pl)UICoordinateSpace","doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIDynamicItem","doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIFocusEnvironment","doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIFocusItem","doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIFocusItemContainer","doc:\/\/com.gamechange.GCCardReader\/objc(pl)UILargeContentViewerItem","doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.gamechange.GCCardReader\/5UIKit23UITraitChangeObservableP","doc:\/\/com.gamechange.GCCardReader\/objc(pl)UITraitEnvironment","doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gccardreader\/mbbarprogressview"]},{"paths":["\/documentation\/gccardreader\/mbbarprogressview"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBarProgressView\/lineColor","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBarProgressView\/progress","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBarProgressView\/progressColor","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBarProgressView\/progressRemainingColor"],"title":"Instance Properties"}],"abstract":[{"text":"A flat bar progress view.","type":"text"}],"identifier":{"url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBarProgressView","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MBBarProgressView","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader"]]},"metadata":{"modules":[{"name":"GCCardReader"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MBBarProgressView","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","title":"MBBarProgressView","navigatorTitle":[{"kind":"identifier","text":"MBBarProgressView"}],"role":"symbol","externalID":"c:objc(cs)MBBarProgressView"},"references":{"doc://com.gamechange.GCCardReader/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://com.gamechange.GCCardReader/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBBarProgressView/progress":{"navigatorTitle":[{"kind":"identifier","text":"progress"}],"role":"symbol","title":"progress","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBarProgressView\/progress","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"progress"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"url":"\/documentation\/gccardreader\/mbbarprogressview\/progress","abstract":[{"type":"text","text":"Progress (0.0 to 1.0)"}]},"doc://com.gamechange.GCCardReader/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.gamechange.GCCardReader/objc(pl)NSCoding":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://com.gamechange.GCCardReader/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://com.gamechange.GCCardReader/SQ":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.gamechange.GCCardReader/SH":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.gamechange.GCCardReader/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.gamechange.GCCardReader/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://com.gamechange.GCCardReader/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://com.gamechange.GCCardReader/objc(pl)UIAppearance":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIAppearance","type":"unresolvable","title":"UIKit.UIAppearance"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBBarProgressView/progressRemainingColor":{"kind":"symbol","navigatorTitle":[{"text":"progressRemainingColor","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBarProgressView\/progressRemainingColor","abstract":[{"text":"Bar background color.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Defaults to clear [UIColor clearColor];"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"progressRemainingColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"title":"progressRemainingColor","url":"\/documentation\/gccardreader\/mbbarprogressview\/progressremainingcolor","type":"topic"},"doc://com.gamechange.GCCardReader/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://com.gamechange.GCCardReader/s8SendableP":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]},"doc://com.gamechange.GCCardReader/objc(pl)NSObject":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.gamechange.GCCardReader/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://com.gamechange.GCCardReader/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIFocusItemContainer","type":"unresolvable","title":"UIKit.UIFocusItemContainer"},"doc://com.gamechange.GCCardReader/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBBarProgressView":{"navigatorTitle":[{"kind":"identifier","text":"MBBarProgressView"}],"role":"symbol","title":"MBBarProgressView","type":"topic","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBarProgressView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBBarProgressView"}],"url":"\/documentation\/gccardreader\/mbbarprogressview","abstract":[{"type":"text","text":"A flat bar progress view."}]},"doc://com.gamechange.GCCardReader/objc(cs)UIView":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(cs)UIView","type":"unresolvable","title":"UIView"},"doc://com.gamechange.GCCardReader/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIDynamicItem","type":"unresolvable","title":"UIKit.UIDynamicItem"},"doc://com.gamechange.GCCardReader/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://com.gamechange.GCCardReader/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://com.gamechange.GCCardReader/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIKit.UICoordinateSpace"},"doc://com.gamechange.GCCardReader/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://com.gamechange.GCCardReader/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIAccessibilityIdentification","type":"unresolvable","title":"UIKit.UIAccessibilityIdentification"},"doc://com.gamechange.GCCardReader/s7CVarArgP":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBBarProgressView/progressColor":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"progressColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"navigatorTitle":[{"kind":"identifier","text":"progressColor"}],"kind":"symbol","type":"topic","title":"progressColor","url":"\/documentation\/gccardreader\/mbbarprogressview\/progresscolor","abstract":[{"text":"Bar progress color.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Defaults to white [UIColor whiteColor]."}],"role":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBarProgressView\/progressColor"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBBarProgressView/lineColor":{"role":"symbol","abstract":[{"type":"text","text":"Bar border line color."},{"type":"text","text":" "},{"type":"text","text":"Defaults to white [UIColor whiteColor]."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lineColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"navigatorTitle":[{"text":"lineColor","kind":"identifier"}],"title":"lineColor","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBarProgressView\/lineColor","url":"\/documentation\/gccardreader\/mbbarprogressview\/linecolor","type":"topic"},"doc://com.gamechange.GCCardReader/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MBBarProgressView"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"MBBarProgressView","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBBarProgressView"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBarProgressView\/lineColor","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBarProgressView\/progress","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBarProgressView\/progressColor","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBarProgressView\/progressRemainingColor"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.gamechange.GCCardReader\/objc(cs)UIView"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBBarProgressView","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBBarProgressView~1progress\/title","value":"progress"},{"value":[{"kind":"identifier","text":"progress"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBBarProgressView~1progress\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBBarProgressView~1progressRemainingColor\/title","value":"progressRemainingColor","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBBarProgressView~1progressRemainingColor\/fragments","value":[{"text":"progressRemainingColor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBBarProgressView\/title","op":"replace","value":"MBBarProgressView"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBBarProgressView\/fragments","value":[{"text":"MBBarProgressView","kind":"identifier"}]},{"value":"progressColor","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBBarProgressView~1progressColor\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBBarProgressView~1progressColor\/fragments","value":[{"text":"progressColor","kind":"identifier"}]},{"value":"lineColor","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBBarProgressView~1lineColor\/title"},{"value":[{"kind":"identifier","text":"lineColor"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBBarProgressView~1lineColor\/fragments"}]}]}