{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBProgressHUDMode"}]}]}],"variants":[{"paths":["\/documentation\/gccardreader\/mbprogresshudmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gccardreader\/mbprogresshudmode"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/annularDeterminate","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/customView","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/determinate","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/determinateHorizontalBar","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/indeterminate","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/text"]},{"title":"Initializers","identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/init(rawValue:)"]},{"generated":true,"identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/Equatable-Implementations","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"kind":"symbol","metadata":{"roleHeading":"Enumeration","title":"MBProgressHUDMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MBProgressHUDMode","kind":"identifier"}],"role":"symbol","externalID":"c:@E@MBProgressHUDMode","modules":[{"name":"GCCardReader"}],"navigatorTitle":[{"text":"MBProgressHUDMode","kind":"identifier"}],"symbolKind":"enum"},"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.gamechange.GCCardReader\/SQ","doc:\/\/com.gamechange.GCCardReader\/SH","doc:\/\/com.gamechange.GCCardReader\/SY","doc:\/\/com.gamechange.GCCardReader\/s8SendableP"],"type":"conformsTo","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader"]]},"sections":[],"references":{"doc://com.gamechange.GCCardReader/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCCardReader\/SQ"},"doc://com.gamechange.GCCardReader/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCCardReader\/SY"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDMode/determinateHorizontalBar":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"determinateHorizontalBar","kind":"identifier"}],"navigatorTitle":[{"text":"MBProgressHUDModeDeterminateHorizontalBar","kind":"identifier"}],"role":"symbol","url":"\/documentation\/gccardreader\/mbprogresshudmode\/determinatehorizontalbar","title":"MBProgressHUDMode.determinateHorizontalBar","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/determinateHorizontalBar","type":"topic","abstract":[{"type":"text","text":"Horizontal progress bar."}]},"doc://com.gamechange.GCCardReader/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCCardReader\/s8SendableP"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDMode/annularDeterminate":{"url":"\/documentation\/gccardreader\/mbprogresshudmode\/annulardeterminate","role":"symbol","title":"MBProgressHUDMode.annularDeterminate","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/annularDeterminate","abstract":[{"type":"text","text":"Ring-shaped progress view."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"annularDeterminate","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDModeAnnularDeterminate"}]},"doc://com.gamechange.GCCardReader/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCCardReader\/SH"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDMode":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode","url":"\/documentation\/gccardreader\/mbprogresshudmode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDMode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MBProgressHUDMode","kind":"identifier"}],"title":"MBProgressHUDMode","kind":"symbol"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDMode/indeterminate":{"title":"MBProgressHUDMode.indeterminate","type":"topic","role":"symbol","abstract":[{"type":"text","text":"UIActivityIndicatorView."}],"url":"\/documentation\/gccardreader\/mbprogresshudmode\/indeterminate","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/indeterminate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"indeterminate"}],"navigatorTitle":[{"text":"MBProgressHUDModeIndeterminate","kind":"identifier"}],"kind":"symbol"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDMode/init(rawValue:)":{"title":"init(rawValue:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/init(rawValue:)","url":"\/documentation\/gccardreader\/mbprogresshudmode\/init(rawvalue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDMode/customView":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"customView"}],"navigatorTitle":[{"text":"MBProgressHUDModeCustomView","kind":"identifier"}],"role":"symbol","url":"\/documentation\/gccardreader\/mbprogresshudmode\/customview","title":"MBProgressHUDMode.customView","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/customView","type":"topic","abstract":[{"type":"text","text":"Shows a custom view."}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDMode/Equatable-Implementations":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/Equatable-Implementations","url":"\/documentation\/gccardreader\/mbprogresshudmode\/equatable-implementations","role":"collectionGroup","title":"Equatable Implementations","kind":"article"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDMode/determinate":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"determinate"}],"navigatorTitle":[{"text":"MBProgressHUDModeDeterminate","kind":"identifier"}],"title":"MBProgressHUDMode.determinate","url":"\/documentation\/gccardreader\/mbprogresshudmode\/determinate","abstract":[{"type":"text","text":"A round, pie-chart like, progress view."}],"role":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/determinate","kind":"symbol","type":"topic"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDMode/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","abstract":[],"kind":"article","url":"\/documentation\/gccardreader\/mbprogresshudmode\/rawrepresentable-implementations","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/RawRepresentable-Implementations","type":"topic","role":"collectionGroup"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDMode/text":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"text"}],"title":"MBProgressHUDMode.text","navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDModeText"}],"url":"\/documentation\/gccardreader\/mbprogresshudmode\/text","type":"topic","role":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/text","abstract":[{"text":"Shows only labels.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"MBProgressHUDMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","value":[{"text":"MBProgressHUDMode","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBProgressHUDMode"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/annularDeterminate","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/customView","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/determinate","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/determinateHorizontalBar","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/indeterminate","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/text"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MBProgressHUDMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"MBProgressHUDModeDeterminateHorizontalBar","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1determinateHorizontalBar\/title"},{"value":[{"text":"MBProgressHUDModeDeterminateHorizontalBar","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1determinateHorizontalBar\/fragments","op":"replace"},{"value":"MBProgressHUDModeAnnularDeterminate","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1annularDeterminate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1annularDeterminate\/fragments","value":[{"text":"MBProgressHUDModeAnnularDeterminate","kind":"identifier"}]},{"value":"MBProgressHUDMode","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode\/fragments","value":[{"kind":"identifier","text":"MBProgressHUDMode"}]},{"value":"MBProgressHUDModeIndeterminate","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1indeterminate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBProgressHUDModeIndeterminate"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1indeterminate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1customView\/title","value":"MBProgressHUDModeCustomView"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1customView\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBProgressHUDModeCustomView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1determinate\/title","value":"MBProgressHUDModeDeterminate"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1determinate\/fragments","op":"replace","value":[{"text":"MBProgressHUDModeDeterminate","kind":"identifier"}]},{"op":"replace","value":"MBProgressHUDModeText","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1text\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1text\/fragments","value":[{"text":"MBProgressHUDModeText","kind":"identifier"}]}]}]}