{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader"]]},"metadata":{"roleHeading":"Type Alias","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBProgressHUDCompletionBlock"}],"title":"MBProgressHUDCompletionBlock","symbolKind":"typealias","modules":[{"name":"GCCardReader"}],"role":"symbol","navigatorTitle":[{"text":"MBProgressHUDCompletionBlock","kind":"identifier"}],"externalID":"c:MBProgressHUD.h@T@MBProgressHUDCompletionBlock"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"MBProgressHUDCompletionBlock","kind":"identifier"},{"text":" = () -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDCompletionBlock","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gccardreader\/mbprogresshudcompletionblock"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gccardreader\/mbprogresshudcompletionblock"]}],"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDCompletionBlock":{"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBProgressHUDCompletionBlock"}],"navigatorTitle":[{"text":"MBProgressHUDCompletionBlock","kind":"identifier"}],"role":"symbol","url":"\/documentation\/gccardreader\/mbprogresshudcompletionblock","title":"MBProgressHUDCompletionBlock","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDCompletionBlock","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"MBProgressHUDCompletionBlock"},{"value":"typealias","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBProgressHUDCompletionBlock","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBProgressHUDCompletionBlock","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"preciseIdentifier":"c:BFv()","text":"void (^)(void)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"MBProgressHUDCompletionBlock","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"MBProgressHUDCompletionBlock","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDCompletionBlock\/title"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDCompletionBlock\/fragments","value":[{"kind":"identifier","text":"MBProgressHUDCompletionBlock"}],"op":"replace"}]}]}