{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Ring-shaped progress view."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/annularDeterminate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"annularDeterminate","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode"]]},"sections":[],"kind":"symbol","metadata":{"externalID":"c:@E@MBProgressHUDMode@MBProgressHUDModeAnnularDeterminate","role":"symbol","title":"MBProgressHUDMode.annularDeterminate","symbolKind":"case","roleHeading":"Case","modules":[{"name":"GCCardReader"}],"navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDModeAnnularDeterminate"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"annularDeterminate","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/gccardreader\/mbprogresshudmode\/annulardeterminate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gccardreader\/mbprogresshudmode\/annulardeterminate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDMode":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode","url":"\/documentation\/gccardreader\/mbprogresshudmode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDMode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MBProgressHUDMode","kind":"identifier"}],"title":"MBProgressHUDMode","kind":"symbol"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDMode/annularDeterminate":{"url":"\/documentation\/gccardreader\/mbprogresshudmode\/annulardeterminate","role":"symbol","title":"MBProgressHUDMode.annularDeterminate","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/annularDeterminate","abstract":[{"type":"text","text":"Ring-shaped progress view."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"annularDeterminate","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDModeAnnularDeterminate"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"MBProgressHUDModeAnnularDeterminate","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MBProgressHUDModeAnnularDeterminate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MBProgressHUDModeAnnularDeterminate"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode\/title","value":"MBProgressHUDMode"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode\/fragments","value":[{"kind":"identifier","text":"MBProgressHUDMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1annularDeterminate\/title","value":"MBProgressHUDModeAnnularDeterminate"},{"value":[{"text":"MBProgressHUDModeAnnularDeterminate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1annularDeterminate\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}