{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/customView"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gccardreader\/mbprogresshudmode\/customview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gccardreader\/mbprogresshudmode\/customview"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode"]]},"abstract":[{"type":"text","text":"Shows a custom view."}],"metadata":{"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDModeCustomView"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customView"}],"title":"MBProgressHUDMode.customView","role":"symbol","symbolKind":"case","modules":[{"name":"GCCardReader"}],"externalID":"c:@E@MBProgressHUDMode@MBProgressHUDModeCustomView"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"customView"}],"platforms":["iOS"]}]}],"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDMode":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode","url":"\/documentation\/gccardreader\/mbprogresshudmode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDMode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MBProgressHUDMode","kind":"identifier"}],"title":"MBProgressHUDMode","kind":"symbol"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDMode/customView":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"customView"}],"navigatorTitle":[{"text":"MBProgressHUDModeCustomView","kind":"identifier"}],"role":"symbol","url":"\/documentation\/gccardreader\/mbprogresshudmode\/customview","title":"MBProgressHUDMode.customView","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/customView","type":"topic","abstract":[{"type":"text","text":"Shows a custom view."}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MBProgressHUDModeCustomView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"MBProgressHUDModeCustomView"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MBProgressHUDModeCustomView","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode\/title","op":"replace","value":"MBProgressHUDMode"},{"value":[{"text":"MBProgressHUDMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1customView\/title","value":"MBProgressHUDModeCustomView"},{"value":[{"text":"MBProgressHUDModeCustomView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1customView\/fragments"}]}]}