{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"determinateHorizontalBar"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"GCCardReader"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"determinateHorizontalBar","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@E@MBProgressHUDMode@MBProgressHUDModeDeterminateHorizontalBar","title":"MBProgressHUDMode.determinateHorizontalBar","symbolKind":"case","role":"symbol","navigatorTitle":[{"text":"MBProgressHUDModeDeterminateHorizontalBar","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/determinateHorizontalBar","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Horizontal progress bar."}],"variants":[{"paths":["\/documentation\/gccardreader\/mbprogresshudmode\/determinatehorizontalbar"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gccardreader\/mbprogresshudmode\/determinatehorizontalbar"]}],"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDMode":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode","url":"\/documentation\/gccardreader\/mbprogresshudmode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDMode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MBProgressHUDMode","kind":"identifier"}],"title":"MBProgressHUDMode","kind":"symbol"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDMode/determinateHorizontalBar":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"determinateHorizontalBar","kind":"identifier"}],"navigatorTitle":[{"text":"MBProgressHUDModeDeterminateHorizontalBar","kind":"identifier"}],"role":"symbol","url":"\/documentation\/gccardreader\/mbprogresshudmode\/determinatehorizontalbar","title":"MBProgressHUDMode.determinateHorizontalBar","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/determinateHorizontalBar","type":"topic","abstract":[{"type":"text","text":"Horizontal progress bar."}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MBProgressHUDModeDeterminateHorizontalBar"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MBProgressHUDModeDeterminateHorizontalBar","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"MBProgressHUDModeDeterminateHorizontalBar","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode\/title","value":"MBProgressHUDMode"},{"op":"replace","value":[{"kind":"identifier","text":"MBProgressHUDMode"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1determinateHorizontalBar\/title","value":"MBProgressHUDModeDeterminateHorizontalBar"},{"value":[{"text":"MBProgressHUDModeDeterminateHorizontalBar","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1determinateHorizontalBar\/fragments"}]}]}