{"variants":[{"paths":["\/documentation\/gccardreader\/mbprogresshudmode\/determinate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gccardreader\/mbprogresshudmode\/determinate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"A round, pie-chart like, progress view."}],"identifier":{"url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/determinate","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"determinate","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode"]]},"metadata":{"modules":[{"name":"GCCardReader"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"determinate","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","title":"MBProgressHUDMode.determinate","navigatorTitle":[{"text":"MBProgressHUDModeDeterminate","kind":"identifier"}],"role":"symbol","externalID":"c:@E@MBProgressHUDMode@MBProgressHUDModeDeterminate"},"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDMode":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode","url":"\/documentation\/gccardreader\/mbprogresshudmode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDMode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MBProgressHUDMode","kind":"identifier"}],"title":"MBProgressHUDMode","kind":"symbol"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDMode/determinate":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"determinate"}],"navigatorTitle":[{"text":"MBProgressHUDModeDeterminate","kind":"identifier"}],"title":"MBProgressHUDMode.determinate","url":"\/documentation\/gccardreader\/mbprogresshudmode\/determinate","abstract":[{"type":"text","text":"A round, pie-chart like, progress view."}],"role":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/determinate","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MBProgressHUDModeDeterminate","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBProgressHUDModeDeterminate","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"MBProgressHUDModeDeterminate"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MBProgressHUDMode","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode\/title"},{"value":[{"text":"MBProgressHUDMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode\/fragments"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1determinate\/title","op":"replace","value":"MBProgressHUDModeDeterminate"},{"op":"replace","value":[{"kind":"identifier","text":"MBProgressHUDModeDeterminate"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1determinate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}