{"metadata":{"title":"MBProgressHUDMode.indeterminate","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indeterminate","kind":"identifier"}],"role":"symbol","externalID":"c:@E@MBProgressHUDMode@MBProgressHUDModeIndeterminate","modules":[{"name":"GCCardReader"}],"navigatorTitle":[{"text":"MBProgressHUDModeIndeterminate","kind":"identifier"}],"symbolKind":"case"},"abstract":[{"type":"text","text":"UIActivityIndicatorView."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gccardreader\/mbprogresshudmode\/indeterminate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gccardreader\/mbprogresshudmode\/indeterminate"]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/indeterminate"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"indeterminate","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDMode":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode","url":"\/documentation\/gccardreader\/mbprogresshudmode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDMode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MBProgressHUDMode","kind":"identifier"}],"title":"MBProgressHUDMode","kind":"symbol"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDMode/indeterminate":{"title":"MBProgressHUDMode.indeterminate","type":"topic","role":"symbol","abstract":[{"type":"text","text":"UIActivityIndicatorView."}],"url":"\/documentation\/gccardreader\/mbprogresshudmode\/indeterminate","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDMode\/indeterminate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"indeterminate"}],"navigatorTitle":[{"text":"MBProgressHUDModeIndeterminate","kind":"identifier"}],"kind":"symbol"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"MBProgressHUDModeIndeterminate"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"MBProgressHUDModeIndeterminate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"MBProgressHUDModeIndeterminate","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBProgressHUDMode","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode\/title"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBProgressHUDMode"}]},{"value":"MBProgressHUDModeIndeterminate","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1indeterminate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBProgressHUDModeIndeterminate"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDMode~1indeterminate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}