{"metadata":{"role":"symbol","modules":[{"name":"GCCardReader"}],"navigatorTitle":[{"text":"animationType","kind":"identifier"}],"externalID":"c:objc(cs)MBProgressHUD(py)animationType","title":"animationType","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animationType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MBProgressHUDAnimation","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBProgressHUDAnimation"}],"symbolKind":"property"},"identifier":{"url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD\/animationType","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"animationType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDAnimation","preciseIdentifier":"c:@E@MBProgressHUDAnimation","text":"MBProgressHUDAnimation"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The animation type that should be used when the HUD is shown and hidden."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gccardreader\/mbprogresshud\/animationtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gccardreader\/mbprogresshud\/animationtype"]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD"]]},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD/animationType":{"abstract":[{"text":"The animation type that should be used when the HUD is shown and hidden.","type":"text"}],"title":"animationType","kind":"symbol","url":"\/documentation\/gccardreader\/mbprogresshud\/animationtype","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"animationType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBProgressHUDAnimation","text":"MBProgressHUDAnimation","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD\/animationType","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"animationType"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDAnimation":{"type":"topic","url":"\/documentation\/gccardreader\/mbprogresshudanimation","title":"MBProgressHUDAnimation","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDAnimation","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MBProgressHUDAnimation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDAnimation"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD":{"navigatorTitle":[{"text":"MBProgressHUD","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gccardreader\/mbprogresshud","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD","kind":"symbol","title":"MBProgressHUD","abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MBProgressHUD","kind":"identifier"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"animationType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"animationType","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDAnimation","preciseIdentifier":"c:@E@MBProgressHUDAnimation","text":"MBProgressHUDAnimation"},{"text":" ","kind":"text"},{"text":"animationType","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"animationType","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD~1animationType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD~1animationType\/fragments","value":[{"kind":"identifier","text":"animationType"}]},{"value":"MBProgressHUDAnimation","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDAnimation\/title"},{"value":[{"text":"MBProgressHUDAnimation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDAnimation\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/title","op":"replace","value":"MBProgressHUD"},{"op":"replace","value":[{"kind":"identifier","text":"MBProgressHUD"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/fragments"}]}]}