{"sections":[],"metadata":{"title":"areDefaultMotionEffectsEnabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"areDefaultMotionEffectsEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Instance Property","modules":[{"name":"GCCardReader"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"defaultMotionEffectsEnabled"}],"role":"symbol","externalID":"c:objc(cs)MBProgressHUD(py)defaultMotionEffectsEnabled"},"abstract":[{"text":"When enabled, the bezel center gets slightly affected by the device accelerometer data.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Has no effect on iOS < 7.0. Defaults to YES."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"areDefaultMotionEffectsEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gccardreader\/mbprogresshud\/aredefaultmotioneffectsenabled"]},{"paths":["\/documentation\/gccardreader\/mbprogresshud\/aredefaultmotioneffectsenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD\/areDefaultMotionEffectsEnabled"},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD"]]},"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD/areDefaultMotionEffectsEnabled":{"abstract":[{"type":"text","text":"When enabled, the bezel center gets slightly affected by the device accelerometer data."},{"type":"text","text":" "},{"type":"text","text":"Has no effect on iOS < 7.0. Defaults to YES."}],"title":"areDefaultMotionEffectsEnabled","kind":"symbol","url":"\/documentation\/gccardreader\/mbprogresshud\/aredefaultmotioneffectsenabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"areDefaultMotionEffectsEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD\/areDefaultMotionEffectsEnabled","type":"topic","role":"symbol","navigatorTitle":[{"text":"defaultMotionEffectsEnabled","kind":"identifier"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD":{"navigatorTitle":[{"text":"MBProgressHUD","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gccardreader\/mbprogresshud","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD","kind":"symbol","title":"MBProgressHUD","abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MBProgressHUD","kind":"identifier"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"defaultMotionEffectsEnabled"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"defaultMotionEffectsEnabled"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"getter","kind":"keyword"},{"kind":"text","text":"="},{"kind":"identifier","text":"areDefaultMotionEffectsEnabled"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"text":"defaultMotionEffectsEnabled","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"defaultMotionEffectsEnabled","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD~1areDefaultMotionEffectsEnabled\/title"},{"value":[{"text":"defaultMotionEffectsEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD~1areDefaultMotionEffectsEnabled\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/title","value":"MBProgressHUD","op":"replace"},{"op":"replace","value":[{"text":"MBProgressHUD","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/fragments"}]}]}