{"variants":[{"paths":["\/documentation\/gccardreader\/mbprogresshud\/bezelview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gccardreader\/mbprogresshud\/bezelview"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"The view containing the labels and indicator (or customView)."}],"identifier":{"url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD\/bezelView","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bezelView","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBBackgroundView","text":"MBBackgroundView","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBackgroundView"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD"]]},"metadata":{"externalID":"c:objc(cs)MBProgressHUD(py)bezelView","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bezelView"},{"text":": ","kind":"text"},{"text":"MBBackgroundView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBBackgroundView"}],"navigatorTitle":[{"kind":"identifier","text":"bezelView"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","title":"bezelView","modules":[{"name":"GCCardReader"}]},"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD":{"navigatorTitle":[{"text":"MBProgressHUD","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gccardreader\/mbprogresshud","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD","kind":"symbol","title":"MBProgressHUD","abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MBProgressHUD","kind":"identifier"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD/bezelView":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bezelView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBBackgroundView","text":"MBBackgroundView"}],"navigatorTitle":[{"kind":"identifier","text":"bezelView"}],"title":"bezelView","url":"\/documentation\/gccardreader\/mbprogresshud\/bezelview","abstract":[{"type":"text","text":"The view containing the labels and indicator (or customView)."}],"role":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD\/bezelView","kind":"symbol","type":"topic"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBBackgroundView":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBBackgroundView","kind":"identifier"}],"navigatorTitle":[{"text":"MBBackgroundView","kind":"identifier"}],"role":"symbol","url":"\/documentation\/gccardreader\/mbbackgroundview","title":"MBBackgroundView","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBackgroundView","type":"topic","abstract":[]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"bezelView","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"bezelView","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBBackgroundView","text":"MBBackgroundView","preciseIdentifier":"c:objc(cs)MBBackgroundView"},{"text":" * ","kind":"text"},{"text":"bezelView","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/title","value":"MBProgressHUD"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/fragments","value":[{"kind":"identifier","text":"MBProgressHUD"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD~1bezelView\/title","value":"bezelView"},{"op":"replace","value":[{"text":"bezelView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD~1bezelView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBBackgroundView\/title","value":"MBBackgroundView"},{"value":[{"text":"MBBackgroundView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBBackgroundView\/fragments"}]}]}