{"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Set bezelView.layer.cornerRadius instead."}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gccardreader\/mbprogresshud\/cornerradius"]},{"paths":["\/documentation\/gccardreader\/mbprogresshud\/cornerradius"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD\/cornerRadius","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD"]]},"metadata":{"externalID":"c:objc(cs)MBProgressHUD(py)cornerRadius","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cornerRadius","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"navigatorTitle":[{"text":"cornerRadius","kind":"identifier"}],"symbolKind":"property","title":"cornerRadius","roleHeading":"Instance Property","platforms":[],"role":"symbol","modules":[{"name":"GCCardReader"}]},"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD":{"navigatorTitle":[{"text":"MBProgressHUD","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gccardreader\/mbprogresshud","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD","kind":"symbol","title":"MBProgressHUD","abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MBProgressHUD","kind":"identifier"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD/cornerRadius":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"navigatorTitle":[{"text":"cornerRadius","kind":"identifier"}],"title":"cornerRadius","url":"\/documentation\/gccardreader\/mbprogresshud\/cornerradius","abstract":[],"role":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD\/cornerRadius","kind":"symbol","deprecated":true,"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"cornerRadius","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"cornerRadius","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier","text":"CGFloat"},{"text":" ","kind":"text"},{"text":"cornerRadius","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/title","value":"MBProgressHUD","op":"replace"},{"op":"replace","value":[{"text":"MBProgressHUD","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/fragments"},{"value":"cornerRadius","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD~1cornerRadius\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD~1cornerRadius\/fragments","value":[{"text":"cornerRadius","kind":"identifier"}]}]}]}