{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"window","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"deprecationSummary":[{"inlineContent":[{"text":"Use initWithView: instead.","type":"text"}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gccardreader\/mbprogresshud\/init(window:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gccardreader\/mbprogresshud\/init(window:)"]}],"metadata":{"role":"symbol","symbolKind":"init","extendedModule":"GCCardReader","modules":[{"name":"GCCardReader"}],"roleHeading":"Initializer","platforms":[],"externalID":"c:objc(cs)MBProgressHUD(im)initWithWindow:","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"window"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithWindow:"}],"title":"init(window:)"},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD\/init(window:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD/init(window:)":{"type":"topic","url":"\/documentation\/gccardreader\/mbprogresshud\/init(window:)","title":"init(window:)","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD\/init(window:)","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"window","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIWindow","kind":"typeIdentifier","text":"UIWindow"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithWindow:"}],"deprecated":true},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD":{"navigatorTitle":[{"text":"MBProgressHUD","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gccardreader\/mbprogresshud","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD","kind":"symbol","title":"MBProgressHUD","abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MBProgressHUD","kind":"identifier"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithWindow:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithWindow:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithWindow:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"window","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD~1init(window:)\/title","op":"replace","value":"initWithWindow:"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD~1init(window:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithWindow:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/title","value":"MBProgressHUD"},{"value":[{"text":"MBProgressHUD","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}