{"abstract":[{"type":"text","text":"The NSProgress object feeding the progress information to the progress indicator."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"progressObject","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Progress","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSProgress"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"progressObject"}],"role":"symbol","externalID":"c:objc(cs)MBProgressHUD(py)progressObject","modules":[{"name":"GCCardReader"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"progressObject"},{"kind":"text","text":": "},{"text":"Progress","preciseIdentifier":"c:objc(cs)NSProgress","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"symbolKind":"property","title":"progressObject","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD\/progressObject","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/gccardreader\/mbprogresshud\/progressobject"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gccardreader\/mbprogresshud\/progressobject"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD/progressObject":{"abstract":[{"text":"The NSProgress object feeding the progress information to the progress indicator.","type":"text"}],"title":"progressObject","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"progressObject","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSProgress","text":"Progress"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"progressObject"}],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD\/progressObject","type":"topic","kind":"symbol","url":"\/documentation\/gccardreader\/mbprogresshud\/progressobject","role":"symbol"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD":{"navigatorTitle":[{"text":"MBProgressHUD","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gccardreader\/mbprogresshud","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD","kind":"symbol","title":"MBProgressHUD","abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MBProgressHUD","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"progressObject","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"progressObject","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSProgress","text":"NSProgress","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"progressObject","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD~1progressObject\/title","value":"progressObject","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"progressObject"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD~1progressObject\/fragments"},{"op":"replace","value":"MBProgressHUD","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/title"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBProgressHUD"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}