{"sections":[],"metadata":{"role":"symbol","platforms":[],"title":"show(animated:whileExecuting:)","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"showAnimated:whileExecutingBlock:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"show","kind":"identifier"},{"kind":"text","text":"("},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"whileExecuting","kind":"externalParam"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"externalID":"c:objc(cs)MBProgressHUD(im)showAnimated:whileExecutingBlock:","modules":[{"name":"GCCardReader"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"whileExecuting","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"block"},{"kind":"text","text":": "},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" () -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use GCD directly."}],"type":"paragraph"}],"identifier":{"url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD\/show(animated:whileExecuting:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/gccardreader\/mbprogresshud\/show(animated:whileexecuting:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gccardreader\/mbprogresshud\/show(animated:whileexecuting:)"]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD"]]},"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD":{"navigatorTitle":[{"text":"MBProgressHUD","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gccardreader\/mbprogresshud","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD","kind":"symbol","title":"MBProgressHUD","abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MBProgressHUD","kind":"identifier"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD/show(animated:whileExecuting:)":{"type":"topic","url":"\/documentation\/gccardreader\/mbprogresshud\/show(animated:whileexecuting:)","title":"show(animated:whileExecuting:)","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD\/show(animated:whileExecuting:)","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"show","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"whileExecuting"},{"kind":"text","text":": () -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"showAnimated:whileExecutingBlock:"}],"deprecated":true},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"showAnimated:whileExecutingBlock:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showAnimated:whileExecutingBlock:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"showAnimated:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"animated"},{"text":" ","kind":"text"},{"text":"whileExecutingBlock:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(void)","preciseIdentifier":"c:BFv()","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"block"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/title","value":"MBProgressHUD"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/fragments","value":[{"text":"MBProgressHUD","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD~1show(animated:whileExecuting:)\/title","value":"showAnimated:whileExecutingBlock:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"showAnimated:whileExecutingBlock:"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD~1show(animated:whileExecuting:)\/fragments"}]}]}