{"metadata":{"title":"show(animated:whileExecuting:completionBlock:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"showAnimated:whileExecutingBlock:completionBlock:"}],"modules":[{"name":"GCCardReader"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)MBProgressHUD(im)showAnimated:whileExecutingBlock:completionBlock:","platforms":[],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"whileExecuting"},{"text":": () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionBlock"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:MBProgressHUD.h@T@MBProgressHUDCompletionBlock","text":"MBProgressHUDCompletionBlock"},{"text":"?)","kind":"text"}]},"deprecationSummary":[{"inlineContent":[{"text":"Use GCD directly.","type":"text"}],"type":"paragraph"}],"kind":"symbol","variants":[{"paths":["\/documentation\/gccardreader\/mbprogresshud\/show(animated:whileexecuting:completionblock:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gccardreader\/mbprogresshud\/show(animated:whileexecuting:completionblock:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD\/show(animated:whileExecuting:completionBlock:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"show","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"whileExecuting"},{"kind":"text","text":" "},{"text":"block","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" () -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionBlock"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":": "},{"text":"MBProgressHUDCompletionBlock","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDCompletionBlock","preciseIdentifier":"c:MBProgressHUD.h@T@MBProgressHUDCompletionBlock","kind":"typeIdentifier"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD":{"navigatorTitle":[{"text":"MBProgressHUD","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gccardreader\/mbprogresshud","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD","kind":"symbol","title":"MBProgressHUD","abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MBProgressHUD","kind":"identifier"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDCompletionBlock":{"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBProgressHUDCompletionBlock"}],"navigatorTitle":[{"text":"MBProgressHUDCompletionBlock","kind":"identifier"}],"role":"symbol","url":"\/documentation\/gccardreader\/mbprogresshudcompletionblock","title":"MBProgressHUDCompletionBlock","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDCompletionBlock","type":"topic","abstract":[]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD/show(animated:whileExecuting:completionBlock:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"whileExecuting"},{"text":": () -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionBlock"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:MBProgressHUD.h@T@MBProgressHUDCompletionBlock","text":"MBProgressHUDCompletionBlock","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"showAnimated:whileExecutingBlock:completionBlock:"}],"role":"symbol","url":"\/documentation\/gccardreader\/mbprogresshud\/show(animated:whileexecuting:completionblock:)","title":"show(animated:whileExecuting:completionBlock:)","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD\/show(animated:whileExecuting:completionBlock:)","type":"topic","deprecated":true,"abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"showAnimated:whileExecutingBlock:completionBlock:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showAnimated:whileExecutingBlock:completionBlock:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"showAnimated:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"kind":"text","text":" "},{"text":"whileExecutingBlock:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv()","kind":"typeIdentifier","text":"void (^)(void)"},{"text":") ","kind":"text"},{"text":"block","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completionBlock:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv()","text":"void (^)(void)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/title","value":"MBProgressHUD"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/fragments","value":[{"text":"MBProgressHUD","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDCompletionBlock\/title","value":"MBProgressHUDCompletionBlock"},{"value":[{"kind":"identifier","text":"MBProgressHUDCompletionBlock"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDCompletionBlock\/fragments"},{"value":"showAnimated:whileExecutingBlock:completionBlock:","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD~1show(animated:whileExecuting:completionBlock:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"showAnimated:whileExecutingBlock:completionBlock:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD~1show(animated:whileExecuting:completionBlock:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}