{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"show","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"whileExecuting"},{"kind":"text","text":" "},{"kind":"internalParam","text":"block"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" () -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"queue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"dispatch_queue_t","preciseIdentifier":"c:@T@dispatch_queue_t"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionBlock"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDCompletionBlock","preciseIdentifier":"c:MBProgressHUD.h@T@MBProgressHUDCompletionBlock","text":"MBProgressHUDCompletionBlock"},{"text":"? = nil)","kind":"text"}]}]}],"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Method","externalID":"c:objc(cs)MBProgressHUD(im)showAnimated:whileExecutingBlock:onQueue:completionBlock:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"show","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"whileExecuting","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"text":"dispatch_queue_t","preciseIdentifier":"c:@T@dispatch_queue_t","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completionBlock","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:MBProgressHUD.h@T@MBProgressHUDCompletionBlock","text":"MBProgressHUDCompletionBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"showAnimated:whileExecutingBlock:onQueue:completionBlock:"}],"platforms":[],"extendedModule":"GCCardReader","title":"show(animated:whileExecuting:on:completionBlock:)","modules":[{"name":"GCCardReader"}],"symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD\/show(animated:whileExecuting:on:completionBlock:)"},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gccardreader\/mbprogresshud\/show(animated:whileexecuting:on:completionblock:)"]},{"paths":["\/documentation\/gccardreader\/mbprogresshud\/show(animated:whileexecuting:on:completionblock:)"],"traits":[{"interfaceLanguage":"occ"}]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use GCD directly."}]}],"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD":{"navigatorTitle":[{"text":"MBProgressHUD","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gccardreader\/mbprogresshud","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD","kind":"symbol","title":"MBProgressHUD","abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MBProgressHUD","kind":"identifier"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD/show(animated:whileExecuting:on:completionBlock:)":{"type":"topic","url":"\/documentation\/gccardreader\/mbprogresshud\/show(animated:whileexecuting:on:completionblock:)","title":"show(animated:whileExecuting:on:completionBlock:)","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD\/show(animated:whileExecuting:on:completionBlock:)","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"show","kind":"identifier"},{"kind":"text","text":"("},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"whileExecuting"},{"text":": () -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@dispatch_queue_t","text":"dispatch_queue_t"},{"text":", ","kind":"text"},{"text":"completionBlock","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:MBProgressHUD.h@T@MBProgressHUDCompletionBlock","text":"MBProgressHUDCompletionBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"showAnimated:whileExecutingBlock:onQueue:completionBlock:","kind":"identifier"}],"deprecated":true},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDCompletionBlock":{"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBProgressHUDCompletionBlock"}],"navigatorTitle":[{"text":"MBProgressHUDCompletionBlock","kind":"identifier"}],"role":"symbol","url":"\/documentation\/gccardreader\/mbprogresshudcompletionblock","title":"MBProgressHUDCompletionBlock","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDCompletionBlock","type":"topic","abstract":[]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"showAnimated:whileExecutingBlock:onQueue:completionBlock:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"showAnimated:whileExecutingBlock:onQueue:completionBlock:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"showAnimated:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"animated"},{"text":" ","kind":"text"},{"text":"whileExecutingBlock:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv()","text":"void (^)(void)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"block","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onQueue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSObject<OS_dispatch_queue>","preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)OS_dispatch_queue"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"queue"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completionBlock:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv()","text":"void (^)(void)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"MBProgressHUD","op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/title"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/fragments","op":"replace","value":[{"text":"MBProgressHUD","kind":"identifier"}]},{"value":"showAnimated:whileExecutingBlock:onQueue:completionBlock:","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD~1show(animated:whileExecuting:on:completionBlock:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"showAnimated:whileExecutingBlock:onQueue:completionBlock:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD~1show(animated:whileExecuting:on:completionBlock:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDCompletionBlock\/title","value":"MBProgressHUDCompletionBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDCompletionBlock\/fragments","value":[{"text":"MBProgressHUDCompletionBlock","kind":"identifier"}]}]}]}