{"identifier":{"url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD\/xOffset","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"xOffset","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"externalID":"c:objc(cs)MBProgressHUD(py)xOffset","navigatorTitle":[{"kind":"identifier","text":"xOffset"}],"roleHeading":"Instance Property","modules":[{"name":"GCCardReader"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"xOffset","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"title":"xOffset","platforms":[],"symbolKind":"property","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Set offset.x instead."}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gccardreader\/mbprogresshud\/xoffset"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gccardreader\/mbprogresshud\/xoffset"]}],"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD":{"navigatorTitle":[{"text":"MBProgressHUD","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gccardreader\/mbprogresshud","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD","kind":"symbol","title":"MBProgressHUD","abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MBProgressHUD","kind":"identifier"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD/xOffset":{"type":"topic","url":"\/documentation\/gccardreader\/mbprogresshud\/xoffset","title":"xOffset","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD\/xOffset","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xOffset","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"xOffset","kind":"identifier"}],"deprecated":true}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"xOffset"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"xOffset"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"text":" ","kind":"text"},{"text":"xOffset","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/title","value":"MBProgressHUD"},{"value":[{"text":"MBProgressHUD","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/fragments"},{"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD~1xOffset\/title","op":"replace","value":"xOffset"},{"value":[{"kind":"identifier","text":"xOffset"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD~1xOffset\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}