{"identifier":{"url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[[]]},"metadata":{"role":"collection","modules":[{"name":"GCCardReader"}],"symbolKind":"module","title":"GCCardReader","externalID":"GCCardReader","roleHeading":"Framework"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or perform OCR with the camera and then validate the result using the ICA API.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gccardreader"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gccardreader"]}],"topicSections":[{"identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/Integration"],"generated":true,"title":"Articles"},{"title":"Classes","identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader"]},{"identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/EIDACardData","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/EIDAHomeAddress","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/EIDANationality","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/EIDAOnlineData","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/EIDAScanResult","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/EIDAWorkAddress"],"title":"Structures"},{"title":"Enumerations","identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GCCardReaderError","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GCDataGroupId","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GCImagePickerError","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GCNFCConnectFailedError","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GCNFCDisplayMessage"]},{"title":"Extended Modules","identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/Combine","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/CoreGraphics","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/CoreML","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/ImageIO","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/Swift","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/UIKit"]}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"anchor":"Overview","type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"The EIDA card contains a lot of information about the user which can be read using the NFC capability of the iPhone. This framework provides a solution for reading the data for iPhone 7 and later models. Note that the iOS version of the device must be over 13.0 for using the NFC functionality. Another function is provided which performs the OCR for the back of the card and extracts the card number, date of birth and expiry date fields which are required as inputs for the NFC method. Also provided are OCR functions which can scan front and back of the EIDA card and extract relevant information. In addition an nProbe() function is provided for validating the EIDA card and returning the data and validity of the card.","type":"text"}]}]}],"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GCCardReaderVersionString":{"abstract":[{"type":"text","text":"Project version string for GCCardReader."}],"url":"\/documentation\/gccardreader\/gccardreaderversionstring","fragments":[{"kind":"identifier","text":"GCCardReaderVersionString"}],"title":"GCCardReaderVersionString","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GCCardReaderVersionString","type":"topic"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"type":"topic","abstract":[{"type":"text","text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or perform OCR with the camera and then validate the result using the ICA API."}],"title":"GCCardReader","role":"collection","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","url":"\/documentation\/gccardreader"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/Integration":{"title":"Integration steps","role":"article","url":"\/documentation\/gccardreader\/integration","abstract":[{"type":"text","text":"This article provides the list of steps that need to be followed to integrate the GCCardReader framework into an app."}],"kind":"article","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/Integration","type":"topic"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/EIDAHomeAddress":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EIDAHomeAddress"}],"kind":"symbol","navigatorTitle":[{"text":"EIDAHomeAddress","kind":"identifier"}],"url":"\/documentation\/gccardreader\/eidahomeaddress","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/EIDAHomeAddress","title":"EIDAHomeAddress","abstract":[{"type":"text","text":"EIDA Card Home Address"}],"type":"topic"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/EIDAScanResult":{"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/EIDAScanResult","title":"EIDAScanResult","navigatorTitle":[{"kind":"identifier","text":"EIDAScanResult"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EIDAScanResult","kind":"identifier"}],"abstract":[{"text":"Model to return OCR scan result","type":"text"}],"type":"topic","url":"\/documentation\/gccardreader\/eidascanresult"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/EIDACardData":{"abstract":[{"text":"EIDA Card Data","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/EIDACardData","navigatorTitle":[{"kind":"identifier","text":"EIDACardData"}],"type":"topic","url":"\/documentation\/gccardreader\/eidacarddata","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EIDACardData"}],"title":"EIDACardData","role":"symbol"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GCNFCDisplayMessage":{"type":"topic","url":"\/documentation\/gccardreader\/gcnfcdisplaymessage","navigatorTitle":[{"text":"GCNFCDisplayMessage","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GCNFCDisplayMessage","kind":"identifier"}],"title":"GCNFCDisplayMessage","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Model to define your messages based on NFC Reader actions."}],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GCNFCDisplayMessage"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/CoreGraphics":{"title":"CoreGraphics","url":"\/documentation\/gccardreader\/coregraphics","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/CoreGraphics","kind":"symbol"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GCImagePickerError":{"url":"\/documentation\/gccardreader\/gcimagepickererror","title":"GCImagePickerError","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GCImagePickerError","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCImagePickerError","kind":"identifier"}],"abstract":[{"text":"GCImagePickerError","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GCImagePickerError"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GCCardReaderError":{"kind":"symbol","title":"GCCardReaderError","role":"symbol","abstract":[{"type":"text","text":"GCCardReaderError"}],"url":"\/documentation\/gccardreader\/gccardreadererror","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GCCardReaderError","type":"topic","navigatorTitle":[{"text":"GCCardReaderError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"GCCardReaderError","kind":"identifier"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GCCardReaderVersionNumber":{"type":"topic","role":"symbol","title":"GCCardReaderVersionNumber","abstract":[{"type":"text","text":"Project version number for GCCardReader."}],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GCCardReaderVersionNumber","kind":"symbol","url":"\/documentation\/gccardreader\/gccardreaderversionnumber","fragments":[{"kind":"identifier","text":"GCCardReaderVersionNumber"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/EIDAWorkAddress":{"type":"topic","abstract":[{"text":"EIDA Card Work Address","type":"text"}],"url":"\/documentation\/gccardreader\/eidaworkaddress","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/EIDAWorkAddress","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EIDAWorkAddress","kind":"identifier"}],"navigatorTitle":[{"text":"EIDAWorkAddress","kind":"identifier"}],"title":"EIDAWorkAddress","role":"symbol","kind":"symbol"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/CoreML":{"kind":"symbol","abstract":[],"title":"CoreML","type":"topic","url":"\/documentation\/gccardreader\/coreml","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/CoreML","role":"collection"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/EIDANationality":{"role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/EIDANationality","url":"\/documentation\/gccardreader\/eidanationality","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"EIDANationality","kind":"identifier"}],"title":"EIDANationality","navigatorTitle":[{"text":"EIDANationality","kind":"identifier"}],"type":"topic"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/ImageIO":{"role":"collection","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/ImageIO","url":"\/documentation\/gccardreader\/imageio","title":"ImageIO","type":"topic"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/Combine":{"url":"\/documentation\/gccardreader\/combine","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/Combine","type":"topic","abstract":[],"role":"collection","title":"Combine"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/EIDAOnlineData":{"title":"EIDAOnlineData","navigatorTitle":[{"text":"EIDAOnlineData","kind":"identifier"}],"url":"\/documentation\/gccardreader\/eidaonlinedata","type":"topic","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EIDAOnlineData","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/EIDAOnlineData","role":"symbol","kind":"symbol"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/Swift":{"abstract":[],"title":"Swift","type":"topic","url":"\/documentation\/gccardreader\/swift","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/Swift","role":"collection"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GCDataGroupId":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"GCDataGroupId","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"GCDataGroupId","kind":"identifier"}],"url":"\/documentation\/gccardreader\/gcdatagroupid","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GCDataGroupId","abstract":[{"type":"text","text":"Data Group ID"}],"role":"symbol","title":"GCDataGroupId"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader":{"kind":"symbol","url":"\/documentation\/gccardreader\/gccardreader","role":"symbol","type":"topic","navigatorTitle":[{"text":"GcCardReader","kind":"identifier"}],"abstract":[{"type":"text","text":"cCCardReader: Defines public class for the framework. Use the shared instance of this to use methods related to card scanning and NFC connection."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GcCardReader","kind":"identifier"}],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader","title":"GcCardReader"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/UIKit":{"url":"\/documentation\/gccardreader\/uikit","role":"collection","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/UIKit","type":"topic","title":"UIKit","abstract":[]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GCNFCConnectFailedError":{"kind":"symbol","navigatorTitle":[{"text":"GCNFCConnectFailedError","kind":"identifier"}],"role":"symbol","url":"\/documentation\/gccardreader\/gcnfcconnectfailederror","title":"GCNFCConnectFailedError","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GCNFCConnectFailedError","abstract":[{"type":"text","text":"NFC Card connection errors."}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GCNFCConnectFailedError","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/Integration"],"title":"Articles","generated":true},{"title":"Classes","identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader"]},{"title":"Variables","identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GCCardReaderVersionNumber","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GCCardReaderVersionString"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1GcCardReader\/title","value":"GcCardReader"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1GcCardReader\/fragments","value":[{"kind":"identifier","text":"GcCardReader"}]}]}]}