{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDDelegate\/hudWasHidden(_:)"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDDelegate"]]},"abstract":[{"type":"text","text":"Called after the HUD was fully hidden from the screen."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hudWasHidden","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hud"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBProgressHUD","kind":"typeIdentifier","text":"MBProgressHUD","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gccardreader\/mbprogresshuddelegate\/hudwashidden(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gccardreader\/mbprogresshuddelegate\/hudwashidden(_:)"]}],"metadata":{"externalID":"c:objc(pl)MBProgressHUDDelegate(im)hudWasHidden:","role":"symbol","title":"hudWasHidden(_:)","modules":[{"name":"GCCardReader"}],"navigatorTitle":[{"kind":"identifier","text":"hudWasHidden:"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hudWasHidden"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBProgressHUD","kind":"typeIdentifier","text":"MBProgressHUD"},{"kind":"text","text":")"}]},"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDDelegate":{"role":"symbol","type":"topic","title":"MBProgressHUDDelegate","url":"\/documentation\/gccardreader\/mbprogresshuddelegate","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBProgressHUDDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBProgressHUDDelegate"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","role":"collection","url":"\/documentation\/gccardreader","title":"GCCardReader","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","type":"topic","abstract":[{"text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or the camera","type":"text"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUDDelegate/hudWasHidden(_:)":{"role":"symbol","url":"\/documentation\/gccardreader\/mbprogresshuddelegate\/hudwashidden(_:)","title":"hudWasHidden(_:)","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUDDelegate\/hudWasHidden(_:)","kind":"symbol","navigatorTitle":[{"text":"hudWasHidden:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hudWasHidden"},{"kind":"text","text":"("},{"text":"MBProgressHUD","preciseIdentifier":"c:objc(cs)MBProgressHUD","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"text":"Called after the HUD was fully hidden from the screen.","type":"text"}],"type":"topic"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/MBProgressHUD":{"navigatorTitle":[{"text":"MBProgressHUD","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gccardreader\/mbprogresshud","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD","kind":"symbol","title":"MBProgressHUD","abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MBProgressHUD","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"hudWasHidden:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"hudWasHidden:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"hudWasHidden:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/MBProgressHUD","text":"MBProgressHUD","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBProgressHUD"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"hud"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"MBProgressHUDDelegate","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDDelegate\/title","op":"replace"},{"op":"replace","value":[{"text":"MBProgressHUDDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDDelegate~1hudWasHidden(_:)\/title","value":"hudWasHidden:"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUDDelegate~1hudWasHidden(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"hudWasHidden:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/title","value":"MBProgressHUD"},{"value":[{"kind":"identifier","text":"MBProgressHUD"}],"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1MBProgressHUD\/fragments"}]}]}